/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmi;

/**
 *
 * @author Alihan
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hoofdmenu_panel = new javax.swing.JPanel();
        sorteerrob_icon_H = new javax.swing.JLabel();
        Sortingrob_button = new javax.swing.JButton();
        Inpakrob_button = new javax.swing.JButton();
        inpakrob_icon_H = new javax.swing.JLabel();
        orders_icon_H = new javax.swing.JLabel();
        Order_button = new javax.swing.JButton();
        Voorraad_button = new javax.swing.JButton();
        voorraad_icon_H = new javax.swing.JLabel();
        Voorraad_panel = new javax.swing.JLayeredPane();
        Voorraad_menu = new javax.swing.JButton();
        voorraad_icon = new javax.swing.JLabel();
        voorraad_titel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Order_panel = new javax.swing.JLayeredPane();
        Order_menu = new javax.swing.JButton();
        order_icon = new javax.swing.JLabel();
        order_titel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Inpakrob_panel = new javax.swing.JLayeredPane();
        inpakrob_menu = new javax.swing.JButton();
        inpakrob_icon = new javax.swing.JLabel();
        inpakrob_titel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        Sorteerrob_panel = new javax.swing.JLayeredPane();
        Sorteerrob_menu = new javax.swing.JButton();
        sorteerrob_icon1 = new javax.swing.JLabel();
        card_panel_startstop_sorteer = new javax.swing.JPanel();
        startknop_panel = new javax.swing.JPanel();
        sorteer_starticon = new javax.swing.JLabel();
        sorteer_startbutton = new javax.swing.JButton();
        stopknop_panel = new javax.swing.JPanel();
        sorteer_stopbutton = new javax.swing.JButton();
        sorteer_stopicon1 = new javax.swing.JLabel();
        sorteerrob_titel = new javax.swing.JLabel();
        sorteer_stopicon = new javax.swing.JLabel();
        inhoud_sorteerrob_panel = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new java.awt.CardLayout());

        hoofdmenu_panel.setBackground(new java.awt.Color(255, 255, 255));
        hoofdmenu_panel.setMaximumSize(new java.awt.Dimension(1000, 700));
        hoofdmenu_panel.setPreferredSize(new java.awt.Dimension(1000, 700));

        sorteerrob_icon_H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Afbeelding1.png"))); // NOI18N
        sorteerrob_icon_H.setName(""); // NOI18N

        Sortingrob_button.setLabel("Sorteerrobot");
        Sortingrob_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sortingrob_buttonActionPerformed(evt);
            }
        });

        Inpakrob_button.setLabel("Inpakrobot");
        Inpakrob_button.setPreferredSize(new java.awt.Dimension(105, 25));
        Inpakrob_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inpakrob_buttonActionPerformed(evt);
            }
        });

        inpakrob_icon_H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Afbeelding2.png"))); // NOI18N
        inpakrob_icon_H.setName(""); // NOI18N

        orders_icon_H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Afbeelding3.png"))); // NOI18N
        orders_icon_H.setName(""); // NOI18N

        Order_button.setLabel("Orders");
        Order_button.setPreferredSize(new java.awt.Dimension(105, 25));
        Order_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_buttonActionPerformed(evt);
            }
        });

        Voorraad_button.setLabel("Voorraad");
        Voorraad_button.setPreferredSize(new java.awt.Dimension(105, 25));
        Voorraad_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voorraad_buttonActionPerformed(evt);
            }
        });

        voorraad_icon_H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Afbeelding4.png"))); // NOI18N
        voorraad_icon_H.setName(""); // NOI18N

        javax.swing.GroupLayout hoofdmenu_panelLayout = new javax.swing.GroupLayout(hoofdmenu_panel);
        hoofdmenu_panel.setLayout(hoofdmenu_panelLayout);
        hoofdmenu_panelLayout.setHorizontalGroup(
            hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoofdmenu_panelLayout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sortingrob_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sorteerrob_icon_H))
                .addGap(27, 27, 27)
                .addGroup(hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Inpakrob_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpakrob_icon_H))
                .addGap(38, 38, 38)
                .addGroup(hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(hoofdmenu_panelLayout.createSequentialGroup()
                        .addComponent(Order_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Voorraad_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hoofdmenu_panelLayout.createSequentialGroup()
                        .addComponent(orders_icon_H)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voorraad_icon_H)))
                .addGap(274, 274, 274))
        );
        hoofdmenu_panelLayout.setVerticalGroup(
            hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoofdmenu_panelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addGroup(hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoofdmenu_panelLayout.createSequentialGroup()
                        .addGroup(hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hoofdmenu_panelLayout.createSequentialGroup()
                                .addComponent(sorteerrob_icon_H)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoofdmenu_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(voorraad_icon_H, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(orders_icon_H, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hoofdmenu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Order_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Sortingrob_button))
                            .addComponent(Voorraad_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoofdmenu_panelLayout.createSequentialGroup()
                        .addComponent(inpakrob_icon_H)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inpakrob_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jPanel1.add(hoofdmenu_panel, "card2");

        Voorraad_panel.setPreferredSize(new java.awt.Dimension(1000, 700));

        Voorraad_menu.setText("Menu");
        Voorraad_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voorraad_menuActionPerformed(evt);
            }
        });

        voorraad_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Afbeelding4 _icoon.png"))); // NOI18N
        voorraad_icon.setName(""); // NOI18N

        voorraad_titel.setBackground(new java.awt.Color(255, 255, 255));
        voorraad_titel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voorraad_titel.setText("Voorraad");
        voorraad_titel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Verandering", "Vorige aantal", "Huidige aantal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable3);

        javax.swing.GroupLayout Voorraad_panelLayout = new javax.swing.GroupLayout(Voorraad_panel);
        Voorraad_panel.setLayout(Voorraad_panelLayout);
        Voorraad_panelLayout.setHorizontalGroup(
            Voorraad_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Voorraad_panelLayout.createSequentialGroup()
                .addComponent(Voorraad_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(voorraad_titel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voorraad_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Voorraad_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255))
        );
        Voorraad_panelLayout.setVerticalGroup(
            Voorraad_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Voorraad_panelLayout.createSequentialGroup()
                .addGroup(Voorraad_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(voorraad_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voorraad_titel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Voorraad_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 297, Short.MAX_VALUE))
        );
        Voorraad_panel.setLayer(Voorraad_menu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Voorraad_panel.setLayer(voorraad_icon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Voorraad_panel.setLayer(voorraad_titel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Voorraad_panel.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(Voorraad_panel, "card6");

        Order_panel.setPreferredSize(new java.awt.Dimension(1000, 700));

        Order_menu.setText("Menu");
        Order_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_menuActionPerformed(evt);
            }
        });

        order_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Afbeelding3 _icoon.png"))); // NOI18N
        order_icon.setName(""); // NOI18N

        order_titel.setBackground(new java.awt.Color(255, 255, 255));
        order_titel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        order_titel.setText("Orders");
        order_titel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ordernr.", "Order", "Progressie", "Lijn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout Order_panelLayout = new javax.swing.GroupLayout(Order_panel);
        Order_panel.setLayout(Order_panelLayout);
        Order_panelLayout.setHorizontalGroup(
            Order_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Order_panelLayout.createSequentialGroup()
                .addComponent(Order_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(order_titel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(order_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Order_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        Order_panelLayout.setVerticalGroup(
            Order_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Order_panelLayout.createSequentialGroup()
                .addGroup(Order_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(order_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(order_titel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Order_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 310, Short.MAX_VALUE))
        );
        Order_panel.setLayer(Order_menu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Order_panel.setLayer(order_icon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Order_panel.setLayer(order_titel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Order_panel.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(Order_panel, "card5");

        Inpakrob_panel.setBackground(new java.awt.Color(255, 102, 102));
        Inpakrob_panel.setPreferredSize(new java.awt.Dimension(1000, 700));

        inpakrob_menu.setText("Menu");
        inpakrob_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpakrob_menuActionPerformed(evt);
            }
        });

        inpakrob_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Afbeelding2 _icoon.png"))); // NOI18N
        inpakrob_icon.setName(""); // NOI18N

        inpakrob_titel.setBackground(new java.awt.Color(255, 255, 255));
        inpakrob_titel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inpakrob_titel.setText("Inpakrobot");
        inpakrob_titel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        jLabel1.setText("Lijn X");

        jLabel2.setText("Lijn Z");

        jLabel3.setText("Lijn Y");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(8)}
            },
            new String [] {
                "Container 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(8)}
            },
            new String [] {
                "Container 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable6);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(8)}
            },
            new String [] {
                "Container 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(8)}
            },
            new String [] {
                "Container 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable7);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(8)}
            },
            new String [] {
                "Container 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable8);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(8)}
            },
            new String [] {
                "Container 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(8)}
            },
            new String [] {
                "Container 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTable10);

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(8)}
            },
            new String [] {
                "Container 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane10.setViewportView(jTable11);

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(8)}
            },
            new String [] {
                "Container 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane11.setViewportView(jTable12);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );

        javax.swing.GroupLayout Inpakrob_panelLayout = new javax.swing.GroupLayout(Inpakrob_panel);
        Inpakrob_panel.setLayout(Inpakrob_panelLayout);
        Inpakrob_panelLayout.setHorizontalGroup(
            Inpakrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inpakrob_panelLayout.createSequentialGroup()
                .addComponent(inpakrob_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(inpakrob_titel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpakrob_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inpakrob_panelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(Inpakrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Inpakrob_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Inpakrob_panelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Inpakrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Inpakrob_panelLayout.createSequentialGroup()
                    .addGap(147, 147, 147)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(596, Short.MAX_VALUE)))
        );
        Inpakrob_panelLayout.setVerticalGroup(
            Inpakrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inpakrob_panelLayout.createSequentialGroup()
                .addGroup(Inpakrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inpakrob_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inpakrob_titel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inpakrob_menu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(Inpakrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Inpakrob_panelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))
                    .addGroup(Inpakrob_panelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(Inpakrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Inpakrob_panelLayout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(499, Short.MAX_VALUE)))
        );
        Inpakrob_panel.setLayer(inpakrob_menu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Inpakrob_panel.setLayer(inpakrob_icon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Inpakrob_panel.setLayer(inpakrob_titel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Inpakrob_panel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Inpakrob_panel.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Inpakrob_panel.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Inpakrob_panel.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Inpakrob_panel.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Inpakrob_panel.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(Inpakrob_panel, "card4");

        Sorteerrob_panel.setBackground(new java.awt.Color(204, 255, 204));
        Sorteerrob_panel.setPreferredSize(new java.awt.Dimension(1000, 700));

        Sorteerrob_menu.setText("Menu");
        Sorteerrob_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sorteerrob_menuActionPerformed(evt);
            }
        });

        sorteerrob_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Afbeelding1_icoon.png"))); // NOI18N
        sorteerrob_icon1.setName(""); // NOI18N

        card_panel_startstop_sorteer.setLayout(new java.awt.CardLayout());

        startknop_panel.setBackground(new java.awt.Color(255, 255, 255));

        sorteer_starticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/startknop.png"))); // NOI18N
        sorteer_starticon.setName(""); // NOI18N

        sorteer_startbutton.setText("Start");
        sorteer_startbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorteer_startbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startknop_panelLayout = new javax.swing.GroupLayout(startknop_panel);
        startknop_panel.setLayout(startknop_panelLayout);
        startknop_panelLayout.setHorizontalGroup(
            startknop_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sorteer_starticon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sorteer_startbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        startknop_panelLayout.setVerticalGroup(
            startknop_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startknop_panelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(sorteer_starticon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sorteer_startbutton))
        );

        card_panel_startstop_sorteer.add(startknop_panel, "card2");

        stopknop_panel.setBackground(new java.awt.Color(255, 255, 255));

        sorteer_stopbutton.setText("Stop");
        sorteer_stopbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorteer_stopbuttonActionPerformed(evt);
            }
        });

        sorteer_stopicon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stopknop.png"))); // NOI18N
        sorteer_stopicon1.setName(""); // NOI18N

        javax.swing.GroupLayout stopknop_panelLayout = new javax.swing.GroupLayout(stopknop_panel);
        stopknop_panel.setLayout(stopknop_panelLayout);
        stopknop_panelLayout.setHorizontalGroup(
            stopknop_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stopknop_panelLayout.createSequentialGroup()
                .addGroup(stopknop_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sorteer_stopbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sorteer_stopicon1))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        stopknop_panelLayout.setVerticalGroup(
            stopknop_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stopknop_panelLayout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(sorteer_stopicon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sorteer_stopbutton))
        );

        card_panel_startstop_sorteer.add(stopknop_panel, "card3");

        sorteerrob_titel.setBackground(new java.awt.Color(255, 255, 255));
        sorteerrob_titel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sorteerrob_titel.setText("Sorteerrobot");
        sorteerrob_titel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        sorteer_stopicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sorteerrobot.png"))); // NOI18N
        sorteer_stopicon.setName(""); // NOI18N

        inhoud_sorteerrob_panel.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Detecteren", "Lijn X", "Lijn Y", "Lijn Z"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(jTable1);

        javax.swing.GroupLayout inhoud_sorteerrob_panelLayout = new javax.swing.GroupLayout(inhoud_sorteerrob_panel);
        inhoud_sorteerrob_panel.setLayout(inhoud_sorteerrob_panelLayout);
        inhoud_sorteerrob_panelLayout.setHorizontalGroup(
            inhoud_sorteerrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inhoud_sorteerrob_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        inhoud_sorteerrob_panelLayout.setVerticalGroup(
            inhoud_sorteerrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inhoud_sorteerrob_panelLayout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jToggleButton1.setText("Inhoud Sorteerrobot:");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Sorteerrob_panelLayout = new javax.swing.GroupLayout(Sorteerrob_panel);
        Sorteerrob_panel.setLayout(Sorteerrob_panelLayout);
        Sorteerrob_panelLayout.setHorizontalGroup(
            Sorteerrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sorteerrob_panelLayout.createSequentialGroup()
                .addComponent(Sorteerrob_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(sorteerrob_titel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sorteerrob_icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sorteerrob_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(card_panel_startstop_sorteer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(sorteer_stopicon)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sorteerrob_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Sorteerrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inhoud_sorteerrob_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Sorteerrob_panelLayout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addGap(208, 208, 208)))
                .addGap(207, 207, 207))
        );
        Sorteerrob_panelLayout.setVerticalGroup(
            Sorteerrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sorteerrob_panelLayout.createSequentialGroup()
                .addGroup(Sorteerrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Sorteerrob_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sorteerrob_icon1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sorteerrob_titel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(Sorteerrob_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Sorteerrob_panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sorteer_stopicon))
                    .addGroup(Sorteerrob_panelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(card_panel_startstop_sorteer, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inhoud_sorteerrob_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Sorteerrob_panel.setLayer(Sorteerrob_menu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sorteerrob_panel.setLayer(sorteerrob_icon1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sorteerrob_panel.setLayer(card_panel_startstop_sorteer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sorteerrob_panel.setLayer(sorteerrob_titel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sorteerrob_panel.setLayer(sorteer_stopicon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sorteerrob_panel.setLayer(inhoud_sorteerrob_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sorteerrob_panel.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(Sorteerrob_panel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void Sorteerrob_menuActionPerformed(java.awt.event.ActionEvent evt) {                                                
        hoofdmenu_panel.setVisible(true);
        Sorteerrob_panel.setVisible(false);
    }                                               

    private void Sortingrob_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        hoofdmenu_panel.setVisible(false);
        Sorteerrob_panel.setVisible(true);
        inhoud_sorteerrob_panel.setVisible(false);
    }                                                 

    private void inpakrob_menuActionPerformed(java.awt.event.ActionEvent evt) {                                              
        hoofdmenu_panel.setVisible(true);
        Inpakrob_panel.setVisible(false);
    }                                             

    private void Inpakrob_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        hoofdmenu_panel.setVisible(false);
        Inpakrob_panel.setVisible(true);
    }                                               

    private void Voorraad_menuActionPerformed(java.awt.event.ActionEvent evt) {                                              
        hoofdmenu_panel.setVisible(true);
        Voorraad_panel.setVisible(false);
    }                                             

    private void Order_menuActionPerformed(java.awt.event.ActionEvent evt) {                                           
        hoofdmenu_panel.setVisible(true);
        Order_panel.setVisible(false);
    }                                          

    private void Order_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        hoofdmenu_panel.setVisible(false);
        Order_panel.setVisible(true);
    }                                            

    private void Voorraad_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        hoofdmenu_panel.setVisible(false);
        Voorraad_panel.setVisible(true);
    }                                               

    private void sorteer_startbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        startknop_panel.setVisible(false);
        stopknop_panel.setVisible(true);
    }                                                   

    private void sorteer_stopbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        startknop_panel.setVisible(true);
        stopknop_panel.setVisible(false);
    }                                                  

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if (!jToggleButton1.isSelected()) {
            inhoud_sorteerrob_panel.setVisible(false);
        } else {
            inhoud_sorteerrob_panel.setVisible(true);
        }
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Inpakrob_button;
    private javax.swing.JLayeredPane Inpakrob_panel;
    private javax.swing.JButton Order_button;
    private javax.swing.JButton Order_menu;
    private javax.swing.JLayeredPane Order_panel;
    private javax.swing.JButton Sorteerrob_menu;
    private javax.swing.JLayeredPane Sorteerrob_panel;
    private javax.swing.JButton Sortingrob_button;
    private javax.swing.JButton Voorraad_button;
    private javax.swing.JButton Voorraad_menu;
    private javax.swing.JLayeredPane Voorraad_panel;
    private javax.swing.JPanel card_panel_startstop_sorteer;
    private javax.swing.JPanel hoofdmenu_panel;
    private javax.swing.JPanel inhoud_sorteerrob_panel;
    private javax.swing.JLabel inpakrob_icon;
    private javax.swing.JLabel inpakrob_icon_H;
    private javax.swing.JButton inpakrob_menu;
    private javax.swing.JLabel inpakrob_titel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel order_icon;
    private javax.swing.JLabel order_titel;
    private javax.swing.JLabel orders_icon_H;
    private javax.swing.JButton sorteer_startbutton;
    private javax.swing.JLabel sorteer_starticon;
    private javax.swing.JButton sorteer_stopbutton;
    private javax.swing.JLabel sorteer_stopicon;
    private javax.swing.JLabel sorteer_stopicon1;
    private javax.swing.JLabel sorteerrob_icon1;
    private javax.swing.JLabel sorteerrob_icon_H;
    private javax.swing.JLabel sorteerrob_titel;
    private javax.swing.JPanel startknop_panel;
    private javax.swing.JPanel stopknop_panel;
    private javax.swing.JLabel voorraad_icon;
    private javax.swing.JLabel voorraad_icon_H;
    private javax.swing.JLabel voorraad_titel;
    // End of variables declaration                   
}
